java:
  version: jdk8u275-b01
  install:
    archive: OpenJDK8U-jdk_x64_linux_hotspot_8u275b01.tar.gz
    url: 'https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u275-b01/OpenJDK8U-jdk_x64_linux_hotspot_8u275b01.tar.gz'
    directory: /usr/share/java